{
    'name': 'oeHealth Extension',
    'version': '1.5',
    'author': "Ehealth Africa / Braincrew Apps(Migrated to Odoo 12)",
    'category': 'Generic Modules/Medical',
    'summary': 'Ehealth Africa extensions to Odoo 12 Hospital Management Solutions',
    'license': 'AGPL-3',
    'depends': [
        'base',
        'sale',
        'purchase',
        'account',
        'product',
        'documents',
        'hr',
        'web',
        'eha_multi_branch',
        'oehealth',
        'mail',
        'point_of_sale',
        'eha_base_extension',
        'sale_subscription_extension',
        'sms_extension',
        'mail_extension',
        'helpdesk',
    ],

    'description': "EHA Clinic extensions to the oehealth Module",
    "website": "https://eha.ng",
    "data": [
        'oeha_helpdesk/data/helpdesk_groups.xml',
        'security/oeh_security.xml',
        'security/ir.model.access.csv',
        'security/ir.rule.xml',
        'oeha_admission/data/sequence.xml',
        'oeha_admission/views/oeh_medical_admission_views.xml',
        'sequence/oeh_sequence.xml',
        'oeh_navigation.xml',
        'ir_config_param.xml',
        'hide_health_center.xml',
        'oeha_calllog/views/oeh_medical_calllog_view.xml',
        'oeha_insurance/views/oeha_insurance.xml',
        'oeha_symptom/views/oeha_medical_symptom.xml',
        'oeha_symptom/data/data.xml',
        'oeha_imaging/views/report_patient_imagingtest.xml',
        'oeha_imaging/reports/oeh_medical_imaging_report.xml',
        'oeha_imaging/views/oeh_medical_imaging_view.xml',
        'oeha_lab/views/oeha_medical_lab_view.xml',
        'oeha_lab/views/third_party_lab_email_template.xml',
        'oeha_lab/views/sample_type_view.xml',
        'oeha_lab/views/oeha_lab_reason.xml',
        'oeha_lab/wizards/atila_import_view.xml',
        'oeha_lab/wizards/batch_lab_mail_view.xml',
        'oeha_lab/data/data.xml',
        'oeha_lab/reports/oeha_medical_label_report_view.xml',
        'oeha_patient/views/oeha_patient_batch_import_view.xml',
        'oeha_patient/views/oeh_patient_medical_diary_view.xml',
        'oeha_patient/wizard/oeha_merge_patient_wizard.xml',
        'oeha_patient/views/oeha_patient_view.xml',
        'oeha_patient/views/base_views.xml',
        'oeh_socioeconomics/views/oeh_medical_socioeconomics_view.xml',
        'oeh_lifestyle/views/oeh_medical_lifestyle_view.xml',
        'oeha_evaluation/views/oeha_medical_evaluation_view.xml',
        'oeha_evaluation/views/oeha_evaluation_template_views.xml',
        'oeha_evaluation/views/oeha_nurse_assessment.xml',
        'oeha_prescription/views/oeha_prescription.xml',
        'oeha_prescription/views/oeha_prescription_labels.xml',
        'oeha_prescription/data/email_template.xml',
        'oeha_prescription/data/cron.xml',
        'oeha_evaluation/views/oeha_covid19_cif_views.xml',
        'oeha_evaluation/views/oeha_cif_report_wizard.xml',
        'oeha_evaluation/data/mail_template.xml',
        'oeha_evaluation/reports/report_covid19_ncdc_form.xml',
        'oeha_appointment/views/oeha_appointment_view.xml',
        'oeha_accounting/views/oeha_invoice.xml',
        'oeha_program/views/oeha_program.xml',
        'config/views/res_users.xml',
        'oeha_physician/views/oeha_physician_view.xml',
        'oeha_lab/views/lab_test_res_config.xml',
        'views/web_tree_dynamic_colored_field.xml',
        'oeha_evaluation/reports/report_visit_summary.xml',
        'oeha_evaluation/views/oeha_evaluation_report.xml',
        'oeha_evaluation/data/oeha_chart_review_ratings.xml',
        'oeha_evaluation/data/care_providers.xml',
        'oeha_evaluation/data/cron.xml',
        'oeha_evaluation/data/ir_config_param.xml',
        'oeha_invoicing/views/oeha_medical_lab_view.xml',
        'oeha_invoicing/views/oeha_medical_pharmacy_view.xml',
        'oeha_invoicing/wizard/confrim_wizard.xml',
        'oeha_lab/views/lab_review_email_template.xml',
        # 'views/backend_assets.xml',
        'oeha_lab/reports/oeha_medical_ncdc_label_report_view.xml',
        'oeha_evaluation/views/oeha_medical_vaccines.xml',
        'wizard/wizard_message_view.xml',
        'wizard/wizard_confirm_appointment.xml',
        'oeha_lab/reports/report_patient_labtest.xml',
        'oeha_lab/reports/report_labtest_summary.xml',
        'oeha_lab/wizards/wizard_batch_print_labtest.xml',
        'oeha_lab/wizards/wizard_epid_report.xml',
        'oeha_evaluation/wizard/oeha_excel_reach_report.xml',
        'oeha_lab/views/oeha_mapping_config_view.xml',
        'oeha_lab/views/oeha_consumables_tracking_views.xml',
        'oeha_lab/wizards/oeha_lab_test_export_views.xml',
    ],
    "images": ['images/main_screenshot.png'],
    "demo": [
    ],
    'test': [
    ],
    'css': [],
    'js': [
    ],
    'qweb': [
    ],
    "assets": {'web.assets_backend': [
        '/oehealth_extension/static/src/js/evaluation_form.js',
        '/oehealth_extension/static/src/css/evaluation_form.scss']},
    "active": False,
    'application': True,
    "sequence": 3
}
##############################################################################
#    Copyright (C) 2018 oeHealth. All Rights Reserved
#    EHA Clinic Extensions to oeHealth, Hospital Management Solutions


