language: python
python:
  - "3.6"

services:
  - docker

cache:
  directories:
    - "$HOME/.cache/pip"

install:
  - pip install awscli ecs-deploy

script:
  - echo "No tests"

deploy:
  - provider: script
    script: "./core-app/scripts/deploy.sh"
    skip_cleanup: true
  #   on:
  #     branch: master
  # - provider: script
  #   script: "./core-app/scripts/deploy.sh"
  #   skip_cleanup: true
  #   on:
  #     branch: develop
  # - provider: script
  #   script: "./core-app/scripts/deploy.sh"
  #   skip_cleanup: true
    on:
      branch: stage
