from . import sale_subscription
from . import sale_order_template
from . import sale_subscription_template
from . import sale
from . import account
from . import product
from . import patient
from . import res_partner
from . import subscription_alert
from . import subscription_plan
from . import subscription_role
from . import subscription_custom_package