upstream odoo {
  server odoo:8069;
}
upstream odoo-longpolling {
  server odoo:8072;
}

server {
  location = /health {
    access_log off;
    return 200;
  }
}

server {
  listen       80;
  charset     utf-8;
  server_name www.eha.ng *.eha.ng;

  proxy_read_timeout 720s;
  proxy_connect_timeout 720s;
  proxy_send_timeout 720s;
  proxy_ignore_client_abort on;
  client_max_body_size 256M;   # adjust to taste

  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header Host $http_host;
  proxy_set_header X-Forwarded-Proto $scheme;

  #charset koi8-r;
  access_log /dev/stdout;
  error_log /dev/stderr info;

  if ($http_x_forwarded_proto != 'https') {
    return 301 https://$host$request_uri;
  }

  location = /health {
    access_log off;
    return 200;
  }

  # set Expires header for static assets
  # location ~* \.(?:ico|css|js|gif|jpe?g|png)$ {
  #     expires 1d;
  #     add_header Pragma public;
  #     add_header Cache-Control "public";
  # }

  # Redirect longpoll requests to odoo longpolling port
  location /longpolling {
    proxy_pass http://odoo-longpolling;
  }

  # Redirect requests to odoo backend server
  location / {
    proxy_redirect off;
    proxy_pass http://odoo;

    # Add HTTP Strict Transport Security for good measure.
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains;";
  }

  # common gzip
  gzip_types text/css text/less text/plain text/xml application/xml application/json application/javascript;
  gzip on;

  error_page   500 502 503 504  /50x.html;
  location = /50x.html {
    root   /usr/share/nginx/html;
  }

  location ~ /\.ht {
    deny  all;
  }
}
