# -*- coding: utf-8 -*-
{
    'name': 'ERP Requests Application',
    'version': '14.0',
    'author': 'Maach Services',
    'description': """An ERP Requests application use to create requests: 
    It can also be used to send requests.""",
    'summary': 'ERP Requests application for Companies etc ',
    'category': 'Base',
    # 'live_test_url': "https://www.youtube.com/watch?v=KEjxieAoGeA&feature=youtu.be",
    'License': 'AGPL-3.0',
    'depends': [
        'base', 'account', 'purchase', 'stock', 'mail', 'hr', 
        'contacts', 'hr_holidays', 'hr_recruitment', 'sale',
        #  'documents', 
        # 'documents_sign', 'documents_hr_recruitment',
        # 'widget_addons',
        'attachment_indexation',
        'ik_multi_branch', 'l10n_uk',
        #  'account_customization',
        ],
    'data': [
        'security/security_group.xml', 
        'sequence/sequence.xml',
        'views/company_memo_view.xml',
        # 'wizard/doc_mgt_config_wizard.xml',
        'views/res_base.xml',
        'views/memo_forward_view.xml',
        'views/memo_config_view.xml',
        'views/user_role_view.xml',
        'views/memo_category.xml',
        'views/account_account_view.xml',
        # 'views/memo_view_document.xml',
        'views/account_move.xml',
        # 'views/asset_view.xml',
        'views/hr_employee.xml',
        # 'views/docum.xml',
        # 'views/document_kanban_view.xml',
        # 'data/document_mgt_system_data.xml',
        'wizard/return_memo_wizard_view.xml',
        'reports/report_memo.xml',
        'views/assets.xml',
        'security/ir.model.access.csv',
        'data/memo_stage.xml',
        'views/memo_fleet.xml',
        'views/memo_fleet maintainance.xml',
        'data/memo_type.xml',
        'data/memo_config_cash_advance.xml',
        'data/memo_config_employee_transfer.xml',
        'data/memo_config_loan.xml',
        'data/memo_config_payment.xml',
        'data/memo_config_procurement.xml',
        'data/ir_cron.xml',
        'wizard/memo_config_duplication_wizard_views.xml',
        'wizard/memo_assign_users.xml',
        # 'data/mail_templates_data.xml'
    ],
    # 'assets': {'web.assets_backend': [
    #     '/company_memo/static/src/js/error_message.js',
    #     # '/company_memo/static/src/js/hide_function.js',
    # ]},
    # 'qweb': [
    #     'static/src/xml/base.xml',
    # ],
    'price': 135.00,
    'sequence': 1,
    'currency': 'EUR',
    'installable': True,
    'auto_install': False,
}
