[options]
addons_path = /mnt/eha-addons/enterprise,/usr/lib/python3/dist-packages/odoo/addons,/mnt/eha-addons/eha-clinic
csv_internal_sep = ,
auto_reload = True
data_dir = /var/lib/odoo
db_maxconn = $DB_CONN
db_port = 5432
; db_template = template1
dbfilter = ^clinic$
demo = {}
email_from = False
geoip_database = /usr/share/GeoIP/GeoLiteCity.dat
import_partial =
limit_memory_hard = $LIMIT_MEMORY_HARD
limit_memory_soft = $LIMIT_MEMORY_SOFT
limit_request = 8192
limit_time_cpu = $LIMIT_CPU
limit_time_real = $LIMIT_CPU_REAL
limit_time_real_cron = -1
list_db = True
log_db = False
log_db_level = warning
log_handler = $LOG_HANDLER
log_level = $LOG_LEVEL
logfile = /dev/stdout
logrotate = False
longpolling_port = 8072
max_cron_threads = $MAX_CRON_THREADS
osv_memory_age_limit = 1.0
osv_memory_count_limit = False
;pg_path = None
pidfile = None
proxy_mode = True
reportgz = False
server_wide_modules = web,base
syslog = False
test_commit = False
test_enable = False
test_file = False
test_report_directory = False
; translate_modules = ['all']
unaccent = False
without_demo = False
workers = $WORKERS_NUMBER
xmlrpc = True
xmlrpc_interface =
xmlrpc_port = 8069
new_relic_config_file = /etc/odoo-newrelic.ini
admin_passwd = $ADMIN_PASSWORD
sentry_dsn = $SENTRY_DSN
sentry_enabled = $SENTRY_ENABLED
