{
    'name': 'Medical Booking',
    'version': '17.0.1.0.0',
    'summary': 'Medical Appointment & Booking Management',
    'description': 'Full-featured booking module for clinics with doctor assignment, branch management, reminders, and REST API.',
    'author': 'Custom Dev',
    'category': 'Healthcare',
    'depends': ['base', 'mail', 'contacts'],
    'data': [
        'security/booking_security.xml',
        'security/ir.model.access.csv',
        'data/booking_sequence.xml',
        'data/booking_cron.xml',
        'data/mail_template.xml',
        'views/booking_category_views.xml',
        'views/booking_views.xml',
        'views/booking_branch_views.xml',
        'views/res_users_views.xml',
        'views/menu_views.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
